#此文件，是放在配置中心中
debug: true
logging:
  level:
    ROOT: 'INFO'  # 可选项 OFF > FATAL > ERROR > WARN > INFO > DEBUG > TRACE > ALL
    org.springframework.cloud: 'INFO'
    com.javafree.cloud: 'INFO'
  config: classpath:logback-spring.xml

server:
  port: 8080 #启动端口

spring:
  application:
    name: javafree-cloud-admin
    thymeleaf:
      cache: false
  datasource:
    #com.mysql.jdbc.Driver和mysql-connector-java 5用。
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javafree8?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始连接数
      max-active: 10 #最大活动连接
      max-wait: 60000 #从池中取连接(没有闲置连接)的最大等待时间,-1表示无限等待
      min-idle: 5 #最小闲置数,小于min-idle连接池会主动创建新的连接
      time-between-eviction-runs-millis: 60000 #清理线程启动的间隔时间,当线程池中没有可用的连接启动清理线程
      min-evictable-idle-time-millis: 300000 #清理线程保持闲置最小时间
      validation-query: SELECT 1  #用于校验连接
      test-on-borrow: false #请求连接时是否校验,比较消耗性能,一般设置false
      test-on-return: false #归还连接时是否校验,比较消耗性能,一般设置false
      test-while-idle: true #清理线程通过validation-query来校验连接是否正常,如果不正常将从连接池中移除
      pool-prepared-statements: true #存储相同逻辑的sql到连接池的缓存中
      #      filters: stat,wall #监控统计web的statement(sql),以及防sql注入的wall
      # 关闭如上配置,可以采用自定义的filter
      filter:
        stat:
          enabled: true #状态监控-->stat
          db-type: mysql
          log-slow-sql: true  #记录超过指定时间的sql到日志中
          slow-sql-millis: 2000
        wall:
          enabled: true #防火墙-->wall
          db-type: mysql
          config:
            delete-allow: true #false禁止删除
            drop-table-allow: false #禁止删除表
      web-stat-filter:
        enabled: true #开启监控uri,默认false
        url-pattern: /* #添加过滤规则
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid" #忽略过滤
      stat-view-servlet:
        enabled: true #开启视图管理界面,默认false
        url-pattern: /druid/* #视图管理界面uri
        login-username: druid #账号
        login-password: 123456 #密码
  #        allow: 127.0.0.1 白名单
  #        deny:  192.168.1.130黑名单
  jpa:
    show-sql: true # 默认false，在日志里显示执行的sql语句
    hibernate:
      ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
      # 解决 pojo对象属性名有下划线，找不到属性问题
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: off  #尽快释放数据库连接资源，不支持jpa的懒加载

  #设置jackson返回时间格式及时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期时间格式
    time-zone: GMT+8  # 北京时区
    default-property-inclusion: non_null # 属性不为空

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev # 服务分组
# swagger配置项
springfox:
  documentation:
    enabled:  false #开发环境打开swagger功能,生产环境要关闭
