apache:
  rocketmq:
    consumer:
      pushConsumer: myConsumer
    producer:
      producerGroup: myProducer
    name-server: localhost:9876 #mq servername 地址端口
    topic: my-topic  #发送的主题
server:
  port: 18080
spring:
  application:
    name: rocketmq-provider